"""
Module contains a dictionary named glyph_dict which maps from
The name of a primitive to a glyph
"""
glyph_dict = {
    'duplicate'       : '.',
    'dupe'            : '.',
    'over'            : ',',
    'flip'            : ':',
    'pop'             : ';',
    'identity'        : '∘',
    'ident'           : '∘',
    'not'             : '¬',
    'sign of'         : '±',
    'negate'          : '¯',
    'abs'             : '⌵',
    'root'            : '√',
    'sine'            : '○',
    'floor'           : '⌊',
    'ceiling'         : '⌈',
    'round'           : '⁅',
    'equals'          : '=',
    'not equal'       : '≠',
    'less than'       : '<',
    'less equal'      : '≤',
    'greater than'    : '>',
    'greater equal'   : '≥',
    'add'             : '+',
    'sub'             : '-',
    'mul'             : '×',
    'div'             : '÷',
    'modulus'         : '◿',
    'power'           : 'ⁿ',
    'logarithm'       : 'ₙ',
    'log'             : 'ₙ',
    'minimum'         : '↧',
    'maximum'         : '↥',
    'arctan'          : '∠',
    'length'          : '⧻',
    'shape'           : '△',
    'range'           : '⇡',
    'first'           : '⊢',
    'reverse'         : '⇌',
    'deshape'         : '♭',
    'bits'            : '⋯',
    'transpose'       : '⍉',
    'rise'            : '⍏',
    'fall'            : '⍖',
    'where'           : '⊚',
    'classify'        : '⊛',
    'deduplicate'     : '⊝',
    'box'             : '□',
    'unbox'           : '⊔',
    'match'           : '≍',
    'couple'          : '⊟',
    'join'            : '⊂',
    'select'          : '⊏',
    'pick'            : '⊡',
    'reshape'         : '↯',
    'take'            : '↙',
    'drop'            : '↘',
    'rotate'          : '↻',
    'windows'         : '◫',
    'keep'            : '▽',
    'find'            : '⌕',
    'member'          : '∊',
    'indexof'         : '⊗',
    'reduce'          : '/',
    'scan'            : '\\',
    'each'            : '∵',
    'rows'            : '≡',
    'distribute'      : '∺',
    'tribute'         : '≐',
    'table'           : '⊞',
    'cross'           : '⊠',
    'repeat'          : '⍥',
    'group'           : '⊕',
    'partition'       : '⊜',
    'pack'            : '⊐',
    'invert'          : '⍘',
    'gap'             : '⋅',
    'dip'             : '⊙',
    'both'            : '∩',
    'fork'            : '⊃',
    'bracket'         : '⊓',
    'under'           : '⍜',
    'fill'            : '⬚',
    'level'           : '≑',
    'fold'            : '∧',
    'combinate'       : '◳',
    'rock'            : '⋄',
    'surface'         : '~',
    'deep'            : '≊',
    'abyss'           : '≃',
    'seabed'          : '∸',
    'bind'            : "'",
    'if'              : '?',
    'try'             : '⍣',
    'assert'          : '⍤',
    'break'           : '⎋',
    'random'          : '⚂',
    'eta'             : 'η',
    'pi'              : 'π',
    'tau'             : 'τ',
    'infinity'        : '∞',
    'trace'           : '⸮',
}